finished, ready for review
danieltichiyama/Challenge-Even-Fibonacci-Numbers pull request #1
Opened 2019-07-06 20:43 UTC by danieltichiyama

finished, ready for review

2019-07-07 00:31 UTC, taesup requested changes

2019-07-07 00:31 UTC, taesup commented on even_fib_nums.js
> +  let arr = [1,1];
Try doing this without using an array but rather three variables, one to keep track of the current fib number, and two others to keep track of the previous two fib numbers.

2019-07-09 23:47 UTC, danieltichiyama commented on even_fib_nums.js
> +  let arr = [1,1];
Hey Ed,

Thanks man, I think I did this for the stretch goal on the bottom.  Do you think I ought to spend time rewriting these in the same way?

2019-07-10 03:05 UTC, taesup commented on even_fib_nums.js
> +  let arr = [1,1];
You don't have to do it immediately, but I would recommend rewriting it.

2019-07-11 06:28 UTC, merged